spring:
  application:
    name: macro-test-consumer
  profiles:
    active: dev
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/,http://127.0.0.1:9001/eureka/
server:
  port: 7300

