eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  server:
    enable-self-preservation: false
---
server:
  port: 9000
spring:
  profiles: dev1
  application:
    name: macro-pub-register-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/,http://127.0.0.1:9001/eureka/
---
server:
  port: 9001
spring:
  profiles: dev2
  application:
    name: macro-pub-register-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/,http://127.0.0.1:9001/eureka/