spring:
  application:
    name: macro-feign-consumer
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/,http://127.0.0.1:9001/eureka/
server:
  port: 7200
feign:
  hystrix:
    enabled: true